config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  get        'signup' =>  'users#new'

  get        'login'  =>  'sessions#new'
  post       'login'  =>  'sessions#create'
  get        'logout' =>  'sessions#destroy'
  #delete

  resources :articles
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save {self.email = email.downcase }
  validates :username,
            presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,
            presence: true,
            uniqueness: {case_sensitive: false},
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
    !!current_user
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @article = Article.paginate(page: params[:page], per_page: 5)
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create 
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            redirect_to @article
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        @article = Article.find(params[:id])
    
        if @article.update(article_params)
          redirect_to @article
        else
          render :edit, status: :unprocessable_entity
        end
     end
     def destroy
        @article = Article.find(params[:id])
        @article.destroy
    
        redirect_to root_path, status: :see_other
      end
    
    private 
     def article_params
        params.require(:article).permit(:title, :body)
     end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "logged in"
      redirect_to user
    else
      flash.now[:alert] = "Invalid credentials"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @articles = Article.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Welcome'
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<%if logged_in? %>
  <h2><%= "Hello " %><%=link_to "#{current_user.username}", user_path(current_user) %></h2>
  <% end %>
<h2> <%= link_to "Users", users_path %></h2>
<p><%= will_paginate @article %><p>
<%@article.each do |it|%>
    <li>
    <%=link_to it.title, it%>
      user: <%= it.user.username %>
    </li>

<%end%>
<br>

<%= link_to "New Article", new_article_path %>
<br>


<% if logged_in? %>
<%= link_to "Logout", logout_path, method: :delete %>
  <%else %>
  <%= link_to "Sign up!", signup_path %>
  <%= link_to "Log in", login_path %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title%></h1>
<p><%= @article.body%></p>
<p>user: <%= @article.user.username %></p>
<li><%= link_to "Home", root_path %></li>
<% if logged_in? && @article.user == current_user%>
    <li><%= link_to "Edit", edit_article_path(@article)%></li>

    <li><%= link_to "Destroy", article_path(@article), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                  } %></li>

<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
    <% @user.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %><br>
    <% @user.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %><br>
    <% @user.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Details</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |it|%>
  <p>
    <li>
      <%=it.username %><br>
      <%="Articles published: #{it.articles.length}" %>
    </li>
  </p>


<%end%>
<%= link_to "New Article", new_article_path %>
<br><br>
<%= link_to "Sign up!", signup_path %>

app/views/users/new.html.erb
<h1>Sign-up</h1>

<%= render "form", article: @article %>

app/views/users/show.html.erb
<h1>User Details</h1>
<p><%= @user.username %></p>
<p><%= @user.email%></p>
<% @user.articles.each do |item| %>
    <%= link_to item.title, item %>
  <%end %>
<p><%= link_to "Edit user", edit_user_path %></p> <br>
<%= link_to "Home", root_path %>
<p><%= link_to "Logout", logout_path, method: :delete %></p>